module.exports = {
  INCOME_CATEGORIES: ["Servis Geliri", "Turizm Geliri", "Diğer Gelir"],
  EXPENSE_CATEGORIES: [
    "Yakıt",
    "Bakım",
    "Lastik",
    "Sigorta",
    "Kasko",
    "Muayene",
    "Ceza",
    "HGS/OGS",
    "Diğer",
  ],
  MAINTENANCE_TYPES: [
    ["yag_bakimi", "Yağ Bakımı"],
    ["lastik", "Lastik"],
    ["fren", "Fren"],
    ["muayene", "Muayene"],
    ["sigorta", "Sigorta"],
    ["periyodik", "Periyodik Bakım"],
    ["diger", "Diğer"],
  ],
  VEHICLE_TARGET: 9,
  UPCOMING_DAYS: 30,
};
